const LOGIN_USER = 'LOGIN_USER';
const ERROR_OCCURRED = 'ERROR_OCCURRED';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const FETCH_TREES = 'FETCH_TREES';
const OPEN_TREE = 'OPEN_TREE';

export {
  LOGIN_USER,
  ERROR_OCCURRED,
  SIGN_UP_SUCCESS,
  FETCH_TREES,
  OPEN_TREE,
};
